Issue 3 user can edit an entry. Edwin Tan
edtan094/code-journal pull request #7
Opened 2021-12-24 06:04 UTC by edtan094

![Code-Journal-issue-3-user-can-edit-an-entry](https://user-images.githubusercontent.com/90667339/147322909-24331e12-ad16-4787-a874-34f664c7f590.gif)

2021-12-24 06:07 UTC, edtan094 commented
![Code-Journal-issue-3-user-can-edit-an-entry-2](https://user-images.githubusercontent.com/90667339/147323161-d51da192-6cab-4f43-9160-2944b7a6c45e.gif)

2021-12-25 05:13 UTC, codingcodymiller requested changes

2021-12-25 05:13 UTC, codingcodymiller commented on js/main.js
> +    for (var dataEntryNumber = 1; dataEntryNumber <= data.entries.length; dataEntryNumber++) {
You should just start `dataEntryNumber` at `0` so you don't need to subtract 1 from it.

2021-12-25 05:13 UTC, codingcodymiller commented on js/main.js
> +    for (var dataEntryNumber = 1; dataEntryNumber <= data.entries.length; dataEntryNumber++) {
Same deal here, just start at 0.

2021-12-26 20:41 UTC, codingcodymiller approved these changes

2021-12-26 20:48 UTC, merged